
name: CI for docker courses

on:
 
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build:
   
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      
      - name: Run a one-line script
        run: echo Check Check 1.. 2.. Noice 

      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file:  ./frontend/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/courses:latest

      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
